const teamMembers = [
  {
    name: "Soumya Mohanty",
    title: "President",
    team: "Executive Body",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119368/Photo_from_Soumya_Mohanty_yv6fsd.jpg",
    description: "",
    linkedin: "https://www.linkedin.com/in/soumya-mohanty-me0409",
    twitter: "https://x.com/home",
  },
  {
    name: "Pratyush Prateek Dash",
    title: "Vice President",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754122254/pratyush__d0cpcx.jpg",
    description: "",
    team: "Executive Body",
    linkedin: "https://www.linkedin.com/in/pratyush-prateek-dash-b8298128a/",
    twitter: "https://x.com/home",
  },
  {
    name: "Sahil Singh",
    title: "General Secretary",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119373/sahil_ixmnve.jpg",
    description: "",
    team: "Executive Body",
    linkedin: "https://linkedin.com/in/",
    twitter: "https://x.com/home",
  },
  {
    name: "Gurudutta Sutar",
    title: "Treasurer",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119361/Gurudutta_taaaxv.jpg",
    description: "",
    team: "Executive Body",
    linkedin: "https://linkedin.com/in/",
    twitter: "https://x.com/home",
  },
  {
    name: "Samidha Behera",
    title: "Sponsorship Head",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119375/samidha_kxwkkb.jpg",
    description: "",
    team: "Executive Body",
    linkedin: "https://www.linkedin.com/in/samidha-behera-09297828a/",
    twitter: "https://x.com/home",
  },
  {
    name: "Nikhil Kumar Dalai",
    title: "PR Head",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754122159/nikhil_co92yf.jpg",
    description: "",
    team: "Executive Body",
    linkedin: "https://www.linkedin.com/in/nikhil-dalai/",
    twitter: "https://x.com/home",
  },
  {
    name: "Aaditya Sahu",
    title: "Captain",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754117969/aaditya_kwvlki.jpg",
    team: "Team Bluestreak",
    description: "",
    linkedin: "https://www.linkedin.com/in/aaditya-sahoo-9605a4279/",
    twitter: "https://x.com/home",
  },
  {
    name: "Komal Hitesh",
    title: "Vice Captain",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754122332/komal_aucker.jpg",
    description: "",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/komal-hitesh-gude-a1402830a/",
    twitter: "https://x.com/home",
  },
  {
    name: "Somanchi Shanmukh",
    title: "Chassis Lead",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119380/shanmukh_abvqy1.jpg",
    description: "",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/shanmukhsomanchi/",
  },
  {
    name: "Aryan Dongare",
    title: "Drivetrain Lead",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119212/aryan_exaoug.jpg",
    description: "",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/aryan-dongare-82aa40325/",
    twitter: "https://x.com/home",
  },
  {
    name: "Mayukh Thakuria",
    title: "Aero Lead",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119366/mayukh_m0mqw1.jpg",
    description: "",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/mayukh-thakuria-509ab8306/",
    twitter: "https://x.com/home",
  },
  {
    name: "Smruti Satabdi Prusty",
    title: "Vehicle Dynamics Lead",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119380/smruti_xxnpss.jpg",
    description: "",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/smruti-satabdi-prusty-a35a3a2a2/",
    twitter: "https://x.com/home",
  },
  {
    name: "Chittaranjan Behera",
    title: "Captain",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119322/Chittaranjan_pccfs6.jpg",
    description: "",
    team: "Team Blueprint",
    linkedin: "https://www.linkedin.com/in/chittaranjan-behera-012b64292/",
    twitter: "https://x.com/home",
  },
  {
    name: "Dharitri",
    title: "Aero Lead",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119358/dharitri__sf7nbd.jpg",
    description: "",
    team: "Team Blueprint",
    linkedin: "https://www.linkedin.com/in/dharitri-pradhan-a92b98269/",
    twitter: "https://x.com/home",
  },
  {
    name: "Nikhil Raj Kiran Sahoo",
    title: "Vice Captain & Electonics Lead",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754122413/raju_lp7qbe.jpg",
    description: "",
    team: "Team Blueprint",
    linkedin: "https://www.linkedin.com/in/nikhil-rajkiran-sahoo-515397277/",
    twitter: "https://x.com/home",
  },
  {
    name: "Soaham Tripathy",
    title: "CAD Lead",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119383/soaham__g318im.jpg",
    description: "",
    team: "Team Blueprint",
    linkedin: "https://www.linkedin.com/in/soaham-tripathy-223582336/",
    twitter: "https://x.com/home",
  },
  {
    name: "Soaham Tripathy",
    title: "Captain",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119383/soaham__g318im.jpg",
    description: "",
    team: "Team Bluebird",
    linkedin: "https://www.linkedin.com/in/soaham-tripathy-223582336/",
    twitter: "https://x.com/home",
  },
  {
    name: "Dev Soni",
    title: "Code Lead",
    img: "https://res.cloudinary.com/dm406z4pf/image/upload/v1754119356/dev_soni_zsexxk.jpg",
    description: "",
    team: "Team Bluebird",
    linkedin: "https://www.linkedin.com/in/dev-soni-80020228a/",
    twitter: "https://x.com/home",
  },
];

export default teamMembers;
